language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libudev-dev
      - libcunit1-dev

before_install:
  - gem install package_cloud

before_script:
  - echo "Fetching checkpatch"
  - wget "https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl" -O checkpatch.pl
  - chmod +x checkpatch.pl
  - ./checkpatch.pl --no-tree -f include/*nvm.h --terse || true
  - ./checkpatch.pl --no-tree -f include/nvm_*.h --terse || true
  - ./checkpatch.pl --no-tree -f src/*.c --terse || true

script:
  - make
  - make pkg
  - package_cloud push slund/liblightnvm/ubuntu/precise /home/travis/build/OpenChannelSSD/liblightnvm/build/liblightnvm-0.1.1-Linux.deb
